### ISSUE TITLE
Лучше не хранить данные большого размера в репозитории, а положить в Releases

### ISSUE THREAD

**Issue by espdev** [Shorstko/GibddStat#1]
> Также всю статистику ДТП можно взять здесь. Guthub не поддерживает файлы размером больше 25 Мб, поэтому выгрузки за 2015-2017 пришлось разделить на два архива ...

Git не предназначен для хранения больших бинарных файлов (если вы не используете [LFS](https://git-lfs.github.com/)). Лучше положите это в релизы. Там и размер файлов может быть больше, не придётся делить на архивы.
https://help.github.com/articles/about-releases/

**Comment by Shorstko** [comment]
Спасибо за совет, научили новому. Данные [переместила](https://github.com/Shorstko/GibddStat/releases). Благодарность в readme )
