### ISSUE TITLE
Добавить про установку requests в мануал

### ISSUE THREAD

**Issue by Shorstko** [Shorstko/GibddStat#2]
По  мотивам комментария на хабре:

> При запуске скрипта вылезла ошибка об отсутствии модуля requests.
> Питон свежескачанный и свежеустановленный.
> Помогло следующее:
> python\scripts\easy_install.exe requests

**Comment by serhii73** [comment]
Было бы правильно добавить файлик `requirements.txt`, где будут стабильные версии библиотек, необходимые для запуска скрипта. Что думаете @Shorstko ?

**Comment by Shorstko** [comment]
@serhii73 , спасибо!
